// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owindhkxfpimjfcmghqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93aW5kaGt4ZnBpbWpmY21naHFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3MDY1NjEsImV4cCI6MjA3NjI4MjU2MX0.H5Q1hqzkn02b8J0l2J99X-mJnjBB7UCBIyGTgAligpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});